In [1]:
import pandas as pd

path = "srcsc-2026-claims-equipment-failure.xlsx"

dfs = pd.read_excel(path, sheet_name=["freq", "sev"])
df_freq = dfs["freq"]
df_sev  = dfs["sev"]

df_freq.head(), df_sev.head()

(   policy_id equipment_id      equipment_type  equipment_age solar_system  \
 0  EF-105325    EQ-722288     ReglAggregators          8.061      Epsilon
 1  EF-136959    EQ-961161          Flux Rider         14.722      Epsilon
 2  EF-045457    EQ-626201  Graviton Extractor         14.411      Epsilon
 3  EF-533949    EQ-967143     ReglAggregators          4.655         Zeta
 4  EF-968417    EQ-796533          Flux Rider         20.346         Zeta

    maintenance_int  usage_int  exposure  claim_count
 0           193.08      19.12     0.874          0.0
 1           715.35      16.07     0.467          1.0
 2           391.95      22.60     0.615          0.0
 3          1466.51       5.04     0.423          0.0
 4          1268.96      20.47     0.769          0.0  ,
        claim_id  claim_seq  policy_id equipment_id   equipment_type  \
 0  EF-C-0000001        1.0  EF-136959    EQ-961161       Flux Rider
 1  EF-C-0000002        1.0  EF-117340    EQ-651029  ReglAggregators
 2  EF-C-0000003        1.0  EF-608351    EQ-094886  ReglAggregators
 3  EF-C-0000004        1.0  EF-786159    EQ-654494     Quantum Bore
 4  EF-C-0000005        1.0  EF-364736    EQ-425368  ReglAggregators

    equipment_age      solar_system  maintenance_int  usage_int  exposure  \
 0         14.722           Epsilon           715.35      16.07     0.467
 1         13.624  Helionis Cluster           530.77       4.10     0.372
 2         12.779              Zeta           635.16      10.23     0.701
 3          6.752              Zeta           572.54      10.44     0.643
 4         13.761  Helionis Cluster           426.02      21.81     0.601

    claim_amount
 0       49193.0
 1       73688.0
 2       50797.0
 3      213915.0
 4       29713.0  )

In [6]:
missing_freq = pd.DataFrame({
    "Missing_Count": df_freq.isna().sum(),
    "Missing_Percent": (df_freq.isna().sum() / len(df_freq))*100
})

missing_freq

                 Missing_Count  Missing_Percent
policy_id                  224         0.235636
equipment_id               221         0.232480
equipment_type             239         0.251415
equipment_age              144         0.151480
solar_system               234         0.246155
maintenance_int            154         0.162000
usage_int                  141         0.148324
exposure                   125         0.131493
claim_count                175         0.184090

In [7]:
missing_sev = pd.DataFrame({
    "Missing_Count": df_sev.isna().sum(),
    "Missing_Percent": (df_sev.isna().sum() / len(df_sev)) * 100
})

missing_sev

                 Missing_Count  Missing_Percent
claim_id                    28         0.338491
claim_seq                   13         0.157157
policy_id                   22         0.265957
equipment_id                15         0.181335
equipment_type              34         0.411025
equipment_age               10         0.120890
solar_system                15         0.181335
maintenance_int             12         0.145068
usage_int                    9         0.108801
exposure                    13         0.157157
claim_amount                16         0.193424

In [8]:
# Cek jumlah sebelum drop
print("Jumlah baris sebelum drop:", len(df_sev))

# Drop baris dengan exposure missing
df_sev = df_sev.dropna(subset=["exposure"])

# Cek jumlah setelah drop
print("Jumlah baris setelah drop:", len(df_sev))

Jumlah baris sebelum drop: 8272
Jumlah baris setelah drop: 8259

In [9]:
df_sev["exposure"].isna().sum()

np.int64(0)